# Generated by Django 5.2.8 on 2025-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('gender_type', models.CharField(choices=[('1', 'male'), ('2', 'famale')], default='2')),
            ],
        ),
    ]
